FROM            mariadb

MAINTAINER      Nigel Jones <jonesn@uk.ibm.com>

# Add dockerize wait tool
RUN apt-get update && apt-get install -y wget
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.1.0/dockerize-linux-amd64-v0.1.0.tar.gz
RUN tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.1.0.tar.gz


# Nothing else needed here yet


